web:
  image: ddiiwoong/exporterhub:build
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  environment:
    - MONGO_HOST=db
    - MONGO_PORT=27017
  links:
    - db
db:
  image: mongo:4.2.1
  ports:
    - "27017:27017"