web:
  image: ddiiwoong/exporterhub:0.31
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  environment:
    - MONGO_HOST=db
    - MONGO_PORT=27017
  links:
    - db
db:
  image: mongo:4.2.1
  restart: always
  environment:
    # MONGO_INITDB_ROOT_USERNAME: admin
    # MONGO_INITDB_ROOT_PASSWORD: 
  volumes:
    - type: bind 
      source: ./data/db
      target: /data/db
  ports:
    - "27017:27017"