version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.72
    working_directory: ~/project
    environment:
      HUGO_BUILD_DIR: ~/project/public
    steps:
      - checkout
      - run: 
          name: Deleting old publication
          command: |
            rm -rf public
            mkdir public
            git worktree prune
            rm -rf .git/worktrees/public/
      - run: 
          name: Checking out gh-pages branch into public
          command: |
            git worktree add -B gh-pages public origin/gh-pages
      - run: 
          name: Removing existing files
          command: |
            rm -rf public/*
      # build with Hugo
      - run: hugo
      - run: 
          name: Removing existing files
          command: |
            cd public && git add --all && git commit -m "Publishing to gh-pages" && cd ..
